Fixed com.sun.max.config.jdk.Package constructor (Windows)
Fixed com.sun.max.config.jdk.Package constructor. We avoid resetting any field in java.lang.UNIXProcess when running on Windows. Attempting to load java.lang.UNIX on Windows caused NoClassDefFoundError when we tried to load com.sun.max.config.jdk.Package class during image generation. As a result problematic classed were not added to Compilation Blacklist and many unexplainable compilation errors were emerging